apiVersion: v1
kind: Service
metadata:
  labels:
    app: echo
    version: v1
  name: echo
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: echo
    version: v1
  sessionAffinity: None
